import math
import torch

from .BaseSampler import BaseSampler


class DikinLangevin(BaseSampler):
    def __init__(self, h, A, b, log_pdf, e=0.0, beta=1.0, use_div=False, x0=None):
        super().__init__(h, A, b, log_pdf, e=e, beta=beta, x0=x0)
        self.use_div = use_div

    def _divergence_from_factor(self, slack, chol):
        """
        Compute
            div C(x) = -2 C(x) sum_i ((a_i^T C(x) a_i) / (b_i - a_i^T x)^3) a_i
        using Cholesky solves, without explicitly forming C(x).
        """
        # AC = A @ Sigma = (Sigma @ A^T)^T
        sigma_a_t = torch.cholesky_solve(self.A.T, chol)
        ac = sigma_a_t.T
        quad = (ac * self.A).sum(dim=1)
        alpha = quad / slack.pow(3)

        rhs = self.A.T @ alpha
        return -2.0 * torch.cholesky_solve(rhs.unsqueeze(1), chol).squeeze(1)

    def _state_stats(self, x):
        """
        Cache everything needed to build proposals and evaluate log q(.|x).
        """
        x_req = x.detach().clone().requires_grad_(True)
        logp = self.log_pdf(x_req)
        grad = torch.autograd.grad(logp, x_req)[0]

        with torch.no_grad():
            slack = self.b - self.A @ x_req
            weight = slack.reciprocal().square()
            Sigma_inv = self.A.T @ (self.A * weight.unsqueeze(1)) + self.e * self.eye
            chol = torch.linalg.cholesky(Sigma_inv)

            # Sigma @ grad
            drift = torch.cholesky_solve(grad.unsqueeze(1), chol).squeeze(1)

            div_c = None
            if self.use_div:
                div_c = self._divergence_from_factor(slack, chol)
                drift = drift + self.beta * div_c

            # log det(Sigma) = - log det(Sigma_inv)
            log_det_sigma = -2.0 * torch.log(torch.diagonal(chol)).sum()

        return {
            "x": x_req.detach(),
            "logp": logp.detach(),
            "grad": grad.detach(),
            "Sigma_inv": Sigma_inv.detach(),
            "chol": chol.detach(),
            "drift": drift.detach(),
            "div_c": None if div_c is None else div_c.detach(),
            "log_det_sigma": log_det_sigma.detach(),
        }

    def _propose(self, state, h):
        noise = torch.randn_like(state["x"])
        # If Sigma_inv = L L^T, then Sigma^{1/2} z can be generated by solving L^T v = z.
        scaled_noise = torch.linalg.solve_triangular(
            state["chol"].T,
            noise.unsqueeze(1),
            upper=True,
        ).squeeze(1)
        return state["x"] + h * state["drift"] + math.sqrt(2.0 * self.beta * h) * scaled_noise

    def _log_proposal_from_state(self, y, state, h):
        mu = state["x"] + h * state["drift"]
        diff = y - mu
        quad = diff @ state["Sigma_inv"] @ diff / (2.0 * self.beta * h)
        return -0.5 * quad - 0.5 * state["log_det_sigma"]

    def acceptance_ratio(self, proposal_state, current_state, h):
        y = proposal_state["x"]
        if not self.is_valid(y):
            return y.new_tensor(0.0)

        log_num = proposal_state["logp"] + self._log_proposal_from_state(current_state["x"], proposal_state, h)
        log_den = current_state["logp"] + self._log_proposal_from_state(y, current_state, h)

        return torch.exp(torch.clamp(log_num - log_den, max=0.0))
